# Generated by Django 3.1.5 on 2021-03-15 12:50

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('kind', models.CharField(max_length=20, verbose_name='类型名')),
                ('logo', models.CharField(max_length=20, verbose_name='类型图标')),
                ('image', models.ImageField(upload_to='kind', verbose_name='商品图片')),
                ('index', models.SmallIntegerField(default=0, verbose_name='展示顺序')),
            ],
            options={
                'verbose_name': '商品种类',
                'verbose_name_plural': '商品种类',
                'db_table': 'goods_kind',
            },
        ),
        migrations.CreateModel(
            name='GoodsSKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=20, verbose_name='具体商品名')),
                ('intro', models.CharField(default='', max_length=256, verbose_name='商品简介')),
                ('price', models.FloatField(max_length=10, verbose_name='价格')),
                ('unit', models.CharField(max_length=12, verbose_name='单位')),
                ('stock', models.CharField(max_length=12, verbose_name='库存')),
                ('is_on_sale', models.BooleanField(choices=[(0, '上架'), (1, '下架')], default=True, verbose_name='上架状态')),
                ('sales_volume', models.CharField(max_length=20, verbose_name='销量')),
                ('image', models.ImageField(upload_to='', verbose_name='图片简介')),
                ('foreign_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodskind', verbose_name='商品种类')),
            ],
            options={
                'verbose_name': '商品SKU',
                'verbose_name_plural': '商品SKU',
                'db_table': 'goods_sku',
            },
        ),
        migrations.CreateModel(
            name='GoodsSPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('spu', models.CharField(max_length=20, verbose_name='商品SPU名称')),
                ('detail', tinymce.models.HTMLField(blank=True, verbose_name='商品详情')),
            ],
            options={
                'verbose_name': '商品SPU',
                'verbose_name_plural': '商品SPU',
                'db_table': 'goods_spu',
            },
        ),
        migrations.CreateModel(
            name='PromotionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('activity', models.CharField(max_length=20, verbose_name='活动名称')),
                ('image', models.ImageField(upload_to='banner', verbose_name='促销商品图')),
                ('url', models.CharField(max_length=256, verbose_name='活动链接')),
                ('index', models.SmallIntegerField(default=0, verbose_name='活动展示顺序')),
            ],
            options={
                'verbose_name': '首页促销商品表',
                'verbose_name_plural': '首页促销商品表',
                'db_table': 'promotion_list',
            },
        ),
        migrations.CreateModel(
            name='PartitionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('display', models.SmallIntegerField(choices=[(0, '文字'), (1, '图片')], default=1, verbose_name='展示类型')),
                ('index', models.SmallIntegerField(default=0, verbose_name='展示顺序')),
                ('foreign_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodskind', verbose_name='商品kind')),
                ('foreign_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodssku', verbose_name='商品sku')),
            ],
            options={
                'verbose_name': '首页商品分区表',
                'verbose_name_plural': '首页商品分区表',
                'db_table': 'partition_list',
            },
        ),
        migrations.AddField(
            model_name='goodssku',
            name='foreign_spu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodsspu', verbose_name='商品spu'),
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('image', models.ImageField(upload_to='goods', verbose_name='图片路径')),
                ('foreign_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodssku', verbose_name='商品sku')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
                'db_table': 'goods_image',
            },
        ),
        migrations.CreateModel(
            name='BannerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('image', models.ImageField(upload_to='banner', verbose_name='轮播商品图片')),
                ('index', models.SmallIntegerField(default=0, verbose_name='展示顺序')),
                ('foreign_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodskind', verbose_name='商品kind')),
            ],
            options={
                'verbose_name': '首页轮播商品表',
                'verbose_name_plural': '首页轮播商品表',
                'db_table': 'banner_list',
            },
        ),
    ]
