# Generated by Django 3.1.5 on 2021-03-02 07:21

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodskind',
            name='index',
            field=models.SmallIntegerField(default=0, verbose_name='展示顺序'),
        ),
        migrations.AlterField(
            model_name='goodsspu',
            name='detail',
            field=tinymce.models.HTMLField(blank=True, verbose_name='商品详情'),
        ),
        migrations.AlterField(
            model_name='partitionlist',
            name='display',
            field=models.SmallIntegerField(choices=[(0, '文字'), (1, '图片')], default=1, verbose_name='展示类型'),
        ),
    ]
