# Generated by Django 3.1.5 on 2021-03-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20210302_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodssku',
            name='intro',
            field=models.CharField(max_length=256, verbose_name='商品简介'),
        ),
    ]
