# Generated by Django 3.1.5 on 2021-03-04 06:07

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20210304_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_content', tinymce.models.HTMLField()),
            ],
        ),
    ]
