# Generated by Django 3.1.5 on 2021-03-04 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_goodsdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoodsDetail',
        ),
    ]
