# Generated by Django 3.1.5 on 2021-02-27 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('quantity', models.CharField(default=1, max_length=12, verbose_name='商品数量')),
                ('unit_price', models.FloatField(verbose_name='商品单价')),
                ('review', models.CharField(max_length=1024, verbose_name='商品评价')),
                ('skuID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodssku', verbose_name='商品SKU')),
            ],
            options={
                'verbose_name': '订单商品信息',
                'verbose_name_plural': '订单商品信息',
                'db_table': 'ItemsInfo',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('orderID', models.OneToOneField(max_length=12, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='order.itemsinfo', verbose_name='订单ID')),
                ('checkout', models.SmallIntegerField(choices=[(1, '微信支付'), (2, '支付宝支付'), (3, '银联支付'), (4, '货到付款')], default=1, verbose_name='支付方式')),
                ('express_fee', models.SmallIntegerField(default=12, verbose_name='快递费用')),
                ('order', models.SmallIntegerField(choices=[(1, '待支付'), (2, '待发货'), (3, '待收货'), (4, '待评价'), (5, '已完成')], default=2, verbose_name='订单状态')),
                ('total', models.CharField(default=1, max_length=12, verbose_name='总数目')),
                ('aggregate_amount', models.FloatField(verbose_name='总金额')),
                ('transaction_code', models.CharField(max_length=128, verbose_name='支付编号')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
                'db_table': 'OrderInfo',
            },
        ),
    ]
