# Generated by Django 3.1.5 on 2021-03-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('qty', models.SmallIntegerField(verbose_name='商品数量')),
                ('price', models.FloatField(default=0, max_length=9, verbose_name='商品单价')),
                ('review', models.CharField(default='', max_length=1024, verbose_name='商品评价')),
            ],
            options={
                'verbose_name': '订单商品信息',
                'verbose_name_plural': '订单商品信息',
                'db_table': 'ItemsInfo',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('order_id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True, verbose_name='订单ID')),
                ('checkout_mode', models.SmallIntegerField(choices=[(1, '微信支付'), (2, '支付宝支付'), (3, '银联支付'), (4, '货到付款')], default=1, verbose_name='支付方式')),
                ('exp_charge', models.SmallIntegerField(default=10, verbose_name='快递费用')),
                ('order_status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '待发货'), (3, '待收货'), (4, '待评价'), (5, '已完成')], default=1, verbose_name='订单状态')),
                ('total', models.SmallIntegerField(verbose_name='总数目')),
                ('aggregate_amount', models.FloatField(max_length=9, verbose_name='总金额')),
                ('transaction_code', models.CharField(default='', max_length=128, verbose_name='支付编号')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
                'db_table': 'OrderInfo',
            },
        ),
    ]
