# Generated by Django 3.1.5 on 2021-02-27 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='addrID',
            field=models.ForeignKey(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='user.address', verbose_name='地址ID'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='userID',
            field=models.ForeignKey(max_length=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID'),
        ),
        migrations.AddField(
            model_name='itemsinfo',
            name='order',
            field=models.ForeignKey(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='order.orderinfo', verbose_name='订单'),
        ),
    ]
