# Generated by Django 3.1.5 on 2021-03-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210227_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsinfo',
            name='review',
            field=models.CharField(default='', max_length=1024, verbose_name='商品评价'),
        ),
    ]
